name: Node.js CI

on:
    workflow_dispatch:

    schedule:
        - cron: "0 23 * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Run the bot
              env:
                  CI: true
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL}}
                  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
              run: |
                  yarn install
                  node .
